#= require "jquery"

#= require "foundation-sites/js/foundation.core"
#= require "foundation-sites/js/foundation.util.box.js"
#= require "foundation-sites/js/foundation.util.keyboard.js"
#= require "foundation-sites/js/foundation.util.mediaQuery.js"
#= require "foundation-sites/js/foundation.util.motion.js"
#= require "foundation-sites/js/foundation.util.nest.js"
#= require "foundation-sites/js/foundation.util.timerAndImageLoader.js"
#= require "foundation-sites/js/foundation.util.touch.js"
#= require "foundation-sites/js/foundation.util.triggers.js"
#= require "foundation-sites/js/foundation.abide"
#= require "initialize"

#= require "extractor"
#= require "header"
#= require "templates/admin-sidebar"
